@baseUrl = http://localhost:3000/api/cartas

### GET - Obtener todas las cartas
# @name getAllCartas
GET {{baseUrl}}
Content-Type: application/json

### POST - Crear una nueva carta
# @name createCarta
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Darth Vader",
  "cartaClass": 1,
  "items": [1, 2],
  "attack": 25,
  "mana": 100,
  "hp": 100,
  "level": 10
}

### (Guardar el ID de la carta creada para usar después)
@id = {{createCarta.response.body.data.id}}

### 🟡 3. GET - Obtener una carta por ID
# @name getOneCarta
GET {{baseUrl}}/{{id}}
Content-Type: application/json

### 🔵 4. PUT - Actualizar una carta existente
# @name updateCarta
PUT {{baseUrl}}/{{id}}
Content-Type: application/json

{
  "name": "Darth Vader - Updated",
  "cartaClass": 5,
  "items": [1, 2],
  "attack": 30,
  "mana": 120,
  "hp": 110,
  "level": 12
}

### DELETE - Eliminar una carta
# @name deleteCarta
DELETE {{baseUrl}}/{{id}}
Content-Type: application/json

### Buscar una carta
GET http://localhost:3000/api/cartas/search/pikachu

### Buscar una carta
GET http://localhost:3000/api/cartas/search/charizard

### Buscar una carta
GET http://localhost:3000/api/cartas/search/bulbasaur


### Buscar carta en TCGPlayer (scraping)
GET http://localhost:3000/api/cartas/search-tcg/pikachu
Content-Type: application/json


### Obtener datos desde una URL de TCGPlayer
GET http://localhost:3000/api/cartas/search-tcg-url?url=https://www.tcgplayer.com/product/197663/pokemon-hidden-fates-pikachu?page=1&Language=English
Content-Type: application/json


### Buscar cartas de Pikachu en TCGPlayer
GET http://localhost:3000/api/cartas/scrape/pikachu
